name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Initial Setup
        uses: actions/checkout@v3
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install Dependencies
        run: |
          sudo apt install libgirepository1.0-dev libgtk-3-0
          pip install -r requirements.txt
      - name: Build
        run: pyinstaller wpplinkmaker.py --onefile
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: wpplinkmaker
          path: dist/*
